class_name Constants
extends Object

const COLLISION_LAYER_CREEP_PATH = 1
const COLLISION_LAYER_CREEPS = 2
const COLLISION_LAYER_STRUCTURES = 3
const COLLISION_LAYER_SHOTS = 4
const COLLISION_LAYER_MAP_AREA = 5
